runtime: nodejs14
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

default_expiration: 365d

handlers:
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/.*
  - url: /(.*\.(css|js))$
    static_files: dist/\1
    upload: dist/.*\.(css|js)$
  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
    expiration: 1d
    secure: always
    redirect_http_response_code: 301
